Made changes to pipeline_example.ipynb as follows: - fixed encoding issue with "errors=replace" - separated mistral and docling extractor code lines (for better overview) - removed hard-coded file and directory name statements. Now both are passed in the very beginning (paper_name, paper_id, suppl_text)
Issues remaining:
- markdown text extraction gives JSON format warning/error ("dspy.adapters.json_adapter") with the following APIs: OpenAI GPTs, Google Gemini. Mistral works, bad produces mostly garbage...
- structured data extraction gives error: unexpected keyword argument 'input_description'. This concerns the make_dspy_synthesis_extractor_signature() and demands for action.